name: Upload Release Artifacts

on:
    push:
        tags:
            - '*'

env:
    TAG: ${{ github.ref_name }}
    BUILD_NUMBER: ${{ github.run_number }}
    MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
    MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
    MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'microsoft'
                  java-version: 21
                  cache: 'gradle'
            - name: Validate Gradle Wrapper
              uses: gradle/actions/wrapper-validation@v4
            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew
            - name: Get current time
              uses: srfrnk/current-time@master
              id: current-time
              with:
                  format: YYYYMMDDHHmmss
            - name: Build with Gradle
              env:
                  BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
              run: ./gradlew assemble --rerun-tasks
            - name: Maven Release
              if: ${{ env.MAVEN_UPLOAD_URL }}
              env:
                  BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
              run: ./gradlew publish
            - name: Publish (GitHub Releases)
              id: publish_github
              uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
              with:
                  github-token: ${{ github.token }}
                  version-type: release
                  files: |
                      build/libs/!(*-@(dev|sources|javadoc|slim)).jar
                      build/libs/*-@(sources|javadoc).jar
            - name: Publish (Fabric)
              id: publish_fabric
              uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
              with:
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
                  version: ${{ github.ref_name }}+Fabric
                  version-type: release
                  files: |
                      build/libs/!(*-@(dev|sources|javadoc|slim)).jar
                      build/libs/*-@(sources|javadoc).jar
            - name: Notify Discord
              uses: Up-Mods/action-discord-release@main
              with:
                  version: ${{ github.ref_name }}
                  webhook-url: ${{ secrets.ANNOUNCEMENT_WEBHOOK_URL }}
                  curseforge-project-id: ${{ steps.publish_fabric.outputs.curseforge-id }}
                  modrinth-project-id: ${{ steps.publish_fabric.outputs.modrinth-id }}
                  thumbnail-url: https://mod-assets.upcraft.dev/promo/armaments/icon_128x.png
